### ISSUE TITLE
Como ven GitHUB para trabajo colaborativo en OpenSource code.

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/pdd6a-archivado#1]
# Si gustan, poner sus comentarios por favor

**Comment by Liryum** [comment]
@IoTeacher Al menos para grupos de trabajo con código extenso, es una buena herramienta, así todos los "Developers" del equipo, tienen acceso al código a editar.

**Comment by IoTeacher** [comment]
# Para @tectijuana/patrones, este es un mensaje grupal

**Comment by tony528** [comment]
_holis_ **hola** **_hello_**

**Comment by cristhiancr56** [comment]
@IoTeacher  # (Y)

**Comment by IoTeacher** [comment]
## Recuerda para subir JPG, solo arrastrar

### el archivo a este bloque.
