### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by Alan8a** [tectijuana/pdd6a-archivado#12]
Permite separar la construcción de objetos complejos de su implementación de modo que un cliente pueda crear estos objetos complejos con implementaciones diferentes;

**Comment by Alan8a** [comment]
@FranciscodaMVP prueba

**Comment by Alan8a** [comment]
## Diagrama UML del patron Builder

![pantallazo](https://cloud.githubusercontent.com/assets/21091540/17875205/439077ca-6885-11e6-8d3d-16a71795a43d.jpg)

**Comment by IoTeacher** [comment]
Falta recortarlo por favor.

http://pixlr.com/editor

**Comment by IoTeacher** [comment]
Debe de recortar para eso un buen editor es http://pixlr.com/editor

**Comment by Alan8a** [comment]
## Diagrama UML del patron Builder

![pantallazo2](https://cloud.githubusercontent.com/assets/21091540/17875296/15adb27c-6886-11e6-85e3-bcfe0e58d979.png)

**Comment by FranciscodaMVP** [comment]
## Ejemplo C

### http://www.tutorialspoint.com/compile_csharp_online.php

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace Rextester
{
    public class Program
{
public static void Main(string[] args)
{
ConstructorDocumentacionVehiculo constructor;
Console.WriteLine("Desea generar " +
"documentación HTML (1) o PDF (2):");
string seleccion = Console.ReadLine();
if (seleccion == "1")
{
constructor = new ConstructorDocumentacionVehiculoHtml();
}
else
{
constructor = new ConstructorDocumentacionVehiculoPdf();
}
Vendedor vendedor = new Vendedor(constructor);
Documentacion documentacion = vendedor.construye("Martín");
documentacion.imprime();
}
}

```
public class Vendedor
```

{
protected ConstructorDocumentacionVehiculo constructor;
public Vendedor(ConstructorDocumentacionVehiculo constructor)
{
this.constructor = constructor;
}
public Documentacion construye(string nombreCliente)
{
constructor.construyeSolicitudPedido(nombreCliente);
constructor.construyeSolicitudMatriculacion
(nombreCliente);
Documentacion documentacion = constructor.resultado();
return documentacion;
}
}

```
public class ConstructorDocumentacionVehiculoPdf :
```

ConstructorDocumentacionVehiculo
{
public ConstructorDocumentacionVehiculoPdf()
{
documentacion = new DocumentacionPdf();
}
public override void construyeSolicitudPedido(string
nombreCliente)
{
string documento;
documento = "<PDF>Solicitud de pedido Cliente: " +
nombreCliente + "</PDF>";
documentacion.agregaDocumento(documento);
}
public override void construyeSolicitudMatriculacion
(string nombreSolicitante)
{
string documento;
    documento =
"<PDF>Solicitud de matriculación Solicitante: " +
nombreSolicitante + "</PDF>";
documentacion.agregaDocumento(documento);
}
}

```
public class ConstructorDocumentacionVehiculoHtml :
```

ConstructorDocumentacionVehiculo
{
public ConstructorDocumentacionVehiculoHtml()
{
documentacion = new DocumentacionHtml();
}
public override void construyeSolicitudPedido(string
nombreCliente)
{
string documento;
documento = "<HTML>Solicitud de pedido Cliente: " +
nombreCliente + "</HTML>";
documentacion.agregaDocumento(documento);
}
public override void construyeSolicitudMatriculacion
(string nombreSolicitante)
{
string documento;
documento =
"<HTML>Solicitud de matriculación Solicitante: " +
nombreSolicitante + "</HTML>";
documentacion.agregaDocumento(documento);
}
}

```
public abstract class ConstructorDocumentacionVehiculo
```

{
    protected Documentacion documentacion;
public abstract void construyeSolicitudPedido(string
nombreCliente);
public abstract void construyeSolicitudMatriculacion
(string nombreSolicitante);
public Documentacion resultado()
{
return documentacion;
}
}

public class DocumentacionPdf : Documentacion
{
public override void agregaDocumento(string documento)
{
if (documento.StartsWith("<PDF>"))
contenido.Add(documento);
}
public override void imprime()
{
Console.WriteLine("Documentación PDF");
foreach (string s in contenido)
Console.WriteLine(s);
}
}

```
public class DocumentacionHtml : Documentacion
```

{
public override void agregaDocumento(string documento)
{
if (documento.StartsWith("<HTML>"))
contenido.Add(documento);
}
public override void imprime()
{
Console.WriteLine("Documentación HTML");
foreach (string s in contenido)
Console.WriteLine(s);
}
}

```
public abstract class Documentacion
```

{
protected IList<string> contenido =
new List<string>();
public abstract void agregaDocumento(string documento);
public abstract void imprime();
}

}

**Comment by FranciscodaMVP** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace Rextester
{
    public class Program
    {
        public static void Main(string[] args)
        {
            // Lets create the Director first
            Manufacturer newManufacturer = new Manufacturer();
            // Lets have the Builder class ready
            IPhoneBuilder phoneBuilder = null;

```
        // Now let us create an android phone
        phoneBuilder = new AndroidPhoneBuilder();
        newManufacturer.Construct(phoneBuilder);
        Console.WriteLine("A new Phone built:\n\n{0}", phoneBuilder.Phone.ToString());

        // Now let us create a Windows Phone
        phoneBuilder = new WindowsPhoneBuilder();
        newManufacturer.Construct(phoneBuilder);
        Console.WriteLine("A new Phone built:\n\n{0}", phoneBuilder.Phone.ToString());
    }
}

public enum ScreenType
```

{
    ScreenType_TOUCH_CAPACITIVE,
    ScreenType_TOUCH_RESISTIVE,
    ScreenType_NON_TOUCH
};

public enum Battery
{
    MAH_1000,
    MAH_1500,
    MAH_2000
};

public enum OperatingSystem
{
    ANDROID,
    WINDOWS_MOBILE,
    WINDOWS_PHONE,
    SYMBIAN
};

public enum Stylus
{
    YES,
    NO
};

```
class MobilePhone
```

{
    // fields to hold the part type
    string phoneName;  
    ScreenType phoneScreen;
    Battery phoneBattery;
    OperatingSystem phoneOS;
    Stylus phoneStylus;

```
public MobilePhone(string name)
{
    phoneName = name;
}

// Public properties to access phone parts

public string PhoneName
{
    get { return phoneName; }            
}

public ScreenType PhoneScreen
{
    get { return phoneScreen; }
    set { phoneScreen = value; }
}        

public Battery PhoneBattery
{
    get { return phoneBattery; }
    set { phoneBattery = value; }
}        

public OperatingSystem PhoneOS
{
    get { return phoneOS; }
    set { phoneOS = value; }
}       

public Stylus PhoneStylus
{
    get { return phoneStylus; }
    set { phoneStylus = value; }
}

// Methiod to display phone details in our own representation
public override string ToString()
{
    return string.Format("Name: {0}\nScreen: {1}\nBattery {2}\nOS: {3}\nStylus: {4}",
        PhoneName, PhoneScreen, PhoneBattery, PhoneOS, PhoneStylus);
}

}

interface IPhoneBuilder
```

{
    void BuildScreen();
    void BuildBattery();
    void BuildOS();
    void BuildStylus();
    MobilePhone Phone { get;}
}

```
class AndroidPhoneBuilder : IPhoneBuilder
```

{
    MobilePhone phone;

```
public AndroidPhoneBuilder()
{
    phone = new MobilePhone("Android Phone");
}

#region IPhoneBuilder Members

public void BuildScreen()
{
    phone.PhoneScreen = ScreenType.ScreenType_TOUCH_RESISTIVE;
}

public void BuildBattery()
{
    phone.PhoneBattery = Battery.MAH_1500;
}

public void BuildOS()
{
    phone.PhoneOS = OperatingSystem.ANDROID;
}

public void BuildStylus()
{
    phone.PhoneStylus = Stylus.YES;
}

// GetResult Method which will return the actual phone
public MobilePhone Phone
{
    get { return phone; }
}

#endregion
```

}

// This is the "ConcreteBuilder" class
class WindowsPhoneBuilder : IPhoneBuilder
{
    MobilePhone phone;

```
public WindowsPhoneBuilder()
{
    phone = new MobilePhone("Windows Phone");
}

#region IPhoneBuilder Members

public void BuildScreen()
{
    phone.PhoneScreen = ScreenType.ScreenType_TOUCH_CAPACITIVE;
}
public void BuildBattery()
{
    phone.PhoneBattery = Battery.MAH_2000;
}

public void BuildOS()
{
    phone.PhoneOS = OperatingSystem.WINDOWS_PHONE;
}

public void BuildStylus()
{
    phone.PhoneStylus = Stylus.NO;
}

// GetResult Method which will return the actual phone
public MobilePhone Phone
{
    get { return phone; }
}

#endregion
```

}

```
class Manufacturer
```

{
    public void Construct(IPhoneBuilder phoneBuilder)
    {
        phoneBuilder.BuildBattery();
        phoneBuilder.BuildOS();
        phoneBuilder.BuildScreen();
        phoneBuilder.BuildStylus();
    }
}

}

**Comment by IoTeacher** [comment]
# Muy original gracias a @Alan8a y @FranciscodaMVP con 100
