### ISSUE TITLE
Flyweight

### ISSUE THREAD

**Issue by cristhiancr56** [tectijuana/pdd6a-archivado#13]
# integrantes

@jhonyboy
El patrón Flyweight (u objeto ligero) sirve para eliminar o reducir la redundancia cuando tenemos gran cantidad de objetos que contienen información idéntica, además de lograr un equilibrio entre flexibilidad y rendimiento (uso de recursos).

**Comment by jhonyboy** [comment]
Buen trabajo compañero @cristhiancr56

**Comment by cristhiancr56** [comment]
![builder_pattern_uml_diagram](https://cloud.githubusercontent.com/assets/16788720/17875002/01808510-6884-11e6-988f-4c49ff3fdb43.jpg)
 EJMPLO DE UML

**Comment by cristhiancr56** [comment]
ejemplo #2 e informacion
flyweight
Motivación

Algunos programas requieren un gran número de objetos que tienen algún estado compartido entre ellos. Considere, por ejemplo, un juego de guerra, donde hay una gran cantidad de objetos soldado; un objeto soldado mantener la representación gráfica de un soldado, soldado de comportamiento tales como el movimiento, y disparando armas, en la salud y la ubicación Además del soldado en el terreno guerra. La creación de un gran número de objetos soldado es una necesidad sin embargo, sería incurrir en un coste enorme de memoria. Tenga en cuenta que si bien la representación y el comportamiento de un soldado es lo mismo su salud y su ubicación pueden variar mucho.


Intención

    La intención de este patrón es utilizar el intercambio para soportar un gran número de objetos que tienen parte de su estado interno en común en el que la otra parte del estado puede variar. 


Implementación
La siguiente figura muestra un diagrama de clases UML para el flyweight:
Flyweight Pattern Implementation - UML Class Diagram

**Comment by cristhiancr56** [comment]
![flyweight-design-pattern-implementation-uml-class-diagram](https://cloud.githubusercontent.com/assets/16788720/17875049/4fc70d0c-6884-11e6-80fa-9a42c50baaca.png)

**Comment by IoTeacher** [comment]
Gracias

**Comment by lalo91** [comment]
oli

**Comment by jhonyboy** [comment]
Ejercicio de ejemplo en C# del patrón
[ejecicio1 ejercicio con patron Flyweight.txt](https://github.com/tectijuana/pdd/files/435620/ejecicio1.ejercicio.con.patron.Flyweight.txt)
 Flyweight

**Comment by cristhiancr56** [comment]
Intencion:

Reducir el numero de objetos detallados de muy bajo nivel en un sistema mediante la comparticion de objetos.

Motivacion:

```
Los caracteres de un procesador de palabras podrian ser objetos.
La cantidad de caracteres en un documento puede ser muy grande.
Cada caracter es compartido por los objetos que lo contienen.
```

**Comment by cristhiancr56** [comment]
Ventajas: Reduce en gran cantidad el peso de los datos en un servidor

Desventajas: Consume un poco más de tiempo para realizar las búsquedas

Pasos para aplicar el patrón

```
Asegúrese que el rendimiento en los objetos es un tema primordial, y si el cliente está dispuesto a asumir el reajuste

Divida el objetivo principal en estados: Estado Intrínseco (elementos que se puedan compartir o son comunes) y Estado Extrínseco (elementos particulares a cada tipo)

Retire los elementos con estado extrínseco de los atributos de la clase, y añádale más bien una llamada a métodos

Crear una fábrica que pueda almacenar y reutilizar las instancias existentes de clases

El cliente debe usar la fábrica en vez de utilizar el operador new si requiere de creación de objetos

El cliente (o un tercero) debe revisar los estados extrínsecos, y reemplazar esos estados a métodos de la clase
```

**Comment by cristhiancr56** [comment]
![flyweith](https://cloud.githubusercontent.com/assets/16788720/17951598/2fcb6a94-6a18-11e6-88c5-7d5e5a967c0f.jpg)

**Comment by cristhiancr56** [comment]
Participantes:

Flyweight: Declara una interfaz a traves de la cual los flyweights pueden recibir y actuar sobre estados no compartidos.

ConcreteFlyweight: Implementa la interfaz Flyweight y almacena los estados compartidos, si los hay. Un objeto ConcreteFlyweight debe ser compartible. Cualquier estado que almacene debe ser intrinseco; es decir, debe ser independiente de su contexto.

UnsharedConcreteFlyweight: No todas las subclases de Flyweight tienen por que ser compartidas. La interfaz Flyweight permite que se comparta; no lo fuerza. Es comun que los objetos de esta clase tengan hijos de la clase ConcreteFlyweight en algun nivel de su estructura.

FlyweightFactory: Crea y gestiona a los objetos flyweight. Garantiza que los objetos flyweight se compartan de forma apropiada. Cuando un cliente solicita un flyweight, el objeto de la clase FlyweightFactory proporciona una instancia existente, o crea una.

Client: Contiene referencias a los flyweights. Calcula o almacena los estados no compartidos de los flyweights.

**Comment by IoTeacher** [comment]
Con 100 @cristhiancr56 y @jhonyboy solamente. Gracias por el tip del portal de corrida de C#
