### ISSUE TITLE
Factory method

### ISSUE THREAD

**Issue by JulioCesar0507** [tectijuana/pdd6a-archivado#15]
Tiene un obejtivo presentar un motodo abstracto para la creacion de un objeto reportando a las suclases concretas la creacion efectiva.

team @JuanSamuelVB
@JC0511

**Comment by IoTeacher** [comment]
@JC0511 dificil de atinar puede darme sus apellidos gracias para marcar la calificacion de c#

**Comment by JulioCesar0507** [comment]
Julio Cesar Perez Cabrera

**Comment by IoTeacher** [comment]
Muchisimas gracias, si fue un reto dar con su nick - nombre.

**Comment by JulioCesar0507** [comment]
Disculpe profesor cree que me pueda agregas a slack?
Para subir el curso ?
Se acuerdas que ayer estaba batallando para entrar...

**Comment by JulioCesar0507** [comment]
Con este correo,   jr_0511@live.com
