### ISSUE TITLE
composite

### ISSUE THREAD

**Issue by damarcusfuentes** [tectijuana/pdd6a-archivado#16]
# composite

**Comment by IoTeacher** [comment]
Falta información del patron y el UML diagrama que esta en el eBook

**Comment by DanielaDiaz** [comment]
proporciona  un  marco  de  diseño  de  una  composición  de  objetos  con  una  profundidad  de 
composición variable, basando el diseño en un árbol

**Comment by DanielaDiaz** [comment]
![umlcomposite](https://cloud.githubusercontent.com/assets/21091563/17902702/c43b4ec4-6914-11e6-8bc2-249adba7eca3.jpg)

**Comment by IoTeacher** [comment]
### @DanielaDiaz  y @damarcusfuentes, Falta Teoria y Falta el programa
