### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by lalo91** [tectijuana/pdd6a-archivado#17]
*_#Proxy: construye un objeto que se substituye por otro objeto y que controla su acceso; 
![screenshot from 2016-08-22 16 29 02](https://cloud.githubusercontent.com/assets/16788782/17875364/73e47d62-6886-11e6-8fda-6bb2eed12bbe.png)
*_Un proxy (representante) es un agente o sustituto autorizado para actuar en nombre de otra persona

**Comment by lalo91** [comment]
1. Participantes
   Los participantes del patrón son los siguientes: 
   ● Sujeto (Animación)  es la interfaz común al proxy y al sujeto real; 
   ● SujetoReal (Vídeo)  es el objeto que el proxy controla y representa; 
   ●
   Proxy (AnimaciónProxy)  es el objeto que se sustituye por el sujeto real. Posee una interfaz idéntica 
   a  este  último  (interfaz  Sujeto ).  Se  encarga  de  crear  y  de  destruir  al  sujeto  real  y  de  delegarle  los 
   mensajes. 
2. Colaboraciones
   El  proxy  recibe  las  llamadas  del  cliente  en  lugar  del  sujeto  real.  Cuando  lo  juzga  apropiado,  delega  estos 
   mensajes en el sujeto real. Debe, en este caso, crear previamente el sujeto real si no está creado ya.

Dominios de aplicación
Los proxys son muy útiles en programación orientada a objetos. Existen distintos tipos de proxy. Vamos a ilustrar 
tres: 

*proxy virtual: permite crear un objeto de tamaño importante en el momento adecuado; 
*proxy  remoto:  permite  acceder  a  un  objeto  ejecutándose  en  otro  entorno.  Este  tipo  de  *proxy  se implementa en sistemas de objetos remotos (CORBA, Java RMI); 
*proxy  de  protección:  permite  securizar  el  acceso  a  un  objeto,  por  ejemplo  mediante  técnicas  de 
autenticación.

**Comment by Yermans** [comment]
Equipo:
@lalo91 @Yermans

**Comment by cristhiancr56** [comment]
HOLA

**Comment by lalo91** [comment]
_**EJEMPLO DE USO PROXY_*

using System;
public class AnimacionProxy : Animacion
{
protected Video video = null;
protected string foto = "mostrar la foto";
public void clic()
{
if (video == null)
{
video = new Video();
video.carga();
}
video.reproduce();
}
public void dibuja()
{
if (video != null)
video.dibuja();
else
- 1 -dibuja(foto);
  }
  public void dibuja(string foto)
  {
  Console.WriteLine(foto);
  }
  }

**Comment by IoTeacher** [comment]
Ahora subir el código (claro que funcione) via ls commandos de Git

**Comment by lalo91** [comment]
A grandes razgos

"El patrón Proxy se utiliza como intermediario para acceder a un objeto, permitiendo controlar el acceso a él. Para ello obliga que las llamadas a un objeto ocurran indirectamente a través de un objeto proxy, que actúa como un sustituto del objeto original, delegando luego las llamadas a los métodos de los objetos respectivos."

**Comment by lalo91** [comment]
![adasd](https://cloud.githubusercontent.com/assets/16788782/17951789/c8fc0b96-6a19-11e6-9872-428e49ff4fd9.gif)

**Comment by lalo91** [comment]
using System;

// MainApp test application 
class MainApp
{
  static void Main()
  {
    // Create proxy and request a service 
    Proxy proxy = new Proxy();
    proxy.Request();

```
// Wait for user 
Console.Read();
```

  }
}

// "Subject" 
abstract class Subject 
{
  public abstract void Request();  
}

// "RealSubject" 
class RealSubject : Subject
{
  public override void Request()
  {
    Console.WriteLine("Called RealSubject.Request()");
  }
}

// "Proxy" 
class Proxy : Subject
{
  RealSubject realSubject;

  public override void Request()
  {
    // Use 'lazy initialization' 
    if (realSubject == null)
    {
      realSubject = new RealSubject();
    }

```
realSubject.Request();
```

  }  
}

**Comment by lalo91** [comment]
examples:
puede explicarse de igual manera aqui

http://tratandodeentenderlo.blogspot.mx/2010/08/patrones-de-diseno-proxy.html

**Comment by lalo91** [comment]
*_proxy remoto: representante local de un objeto remoto.
*_proxy virtual: crea objetos costosos bajo demanda (como la clase ImagenProxy en el ejemplo de motivación).
**proxy de protección: controla el acceso al objeto origina

**Comment by lalo91** [comment]
:)

**Comment by IoTeacher** [comment]
Gracias con 100 ambos

**Comment by cristhiancr56** [comment]
sos perfectos
como oracle
