### ISSUE TITLE
facade

### ISSUE THREAD

**Issue by fxrnxndx** [tectijuana/pdd6a-archivado#21]
Se aplicará el patrón fachada cuando se necesite proporcionar una interfaz simple para un subsistema complejo, o cuando se quiera estructurar varios subsistemas en capas, ya que las fachadas serían el punto de entrada a cada nivel. Otro escenario proclive para su aplicación surge de la necesidad de desacoplar un sistema de sus clientes y de otros subsistemas, haciéndolo más independiente, portable y reutilizable (esto es, reduciendo dependencias entre los subsistemas y los clientes).

La principal ventaja del patrón fachada consiste en que para modificar las clases de los subsistemas, sólo hay que realizar cambios en la interfaz/fachada, y los clientes pueden permanecer ajenos a ello. Además, y como se mencionó anteriormente, los clientes no necesitan conocer las clases que hay tras dicha interfaz.

Como inconveniente, si se considera el caso de que varios clientes necesiten acceder a subconjuntos diferentes de la funcionalidad que provee el sistema, podrían acabar usando sólo una pequeña parte de la fachada, por lo que sería conveniente utilizar varias fachadas más específicas en lugar de una única global.
![facadedesignpattern](https://cloud.githubusercontent.com/assets/21113497/17913246/8c43eb00-694d-11e6-86a4-3843acb301a4.png)

**Comment by fxrnxndx** [comment]
using System;

public class Test
{
    public static void Main()
    {
        // your code goes here
IAcelerador acelerador = new Acelerador();
IEmbrague embrague = new Embrague();
IPalancaCambios palancaCambios = new PalancaCambios();

acelerador.SoltarAcelerador();
embrague.PresionarEmbrague();
palancaCambios.PuntoMuerto();
palancaCambios.InsertarVelocidad(1);
embrague.SoltarEmbrague();
acelerador.PresionarAcelerador();
    }
}
public interface IPalancaCambios
{
    void InsertarVelocidad(int velocidad);
    void PuntoMuerto();
    int GetVelocidadActual();
}
public interface IEmbrague
{
    void PresionarEmbrague();
    void SoltarEmbrague();
}
public interface IAcelerador
{
    void PresionarAcelerador();
    void SoltarAcelerador();
}

public class PalancaCambios : IPalancaCambios
{
    private int _velocidadActual;

```
#region IPalancaCambios Members

public void InsertarVelocidad(int velocidad)
{
    Console.WriteLine("Introduciendo marcha " + velocidad);
    this._velocidadActual = velocidad;
}

public void PuntoMuerto()
{
   Console.WriteLine("Sacando velocidad " + this._velocidadActual);
   this._velocidadActual = 0;
}

public int GetVelocidadActual()
{
    return _velocidadActual;
}

#endregion
```

}

public class Embrague : IEmbrague
{
    #region IEmbrague Members

```
public void PresionarEmbrague()
{
    Console.WriteLine("Embrague presionado");
}

public void SoltarEmbrague()
{
    Console.WriteLine("Embrague suelto");
}

#endregion
```

}

public class Acelerador : IAcelerador
{
    #region IAcelerador Members

```
public void PresionarAcelerador()
{
    Console.WriteLine("Acelerador presionado");
}

public void SoltarAcelerador()
{
    Console.WriteLine("Acelerador levantado");
}

#endregion
```

}

**Comment by IoTeacher** [comment]
@fxrnxndx @ivanmr232 con 100 gracias si lo lograron recordar.

**Comment by IoTeacher** [comment]
@ivanmr232 cual es el nombre de @fxrnxndx ? dificil atinarle.
