### ISSUE TITLE
flyweight

### ISSUE THREAD

**Issue by cristhiancr56** [tectijuana/pdd6a-archivado#26]
El patrón Flyweight (u objeto ligero) sirve para eliminar o reducir la redundancia cuando tenemos gran cantidad de objetos que contienen información idéntica, además de lograr un equilibrio entre flexibilidad y rendimiento (uso de recursos).

Intencion:

Reducir el numero de objetos detallados de muy bajo nivel en un sistema mediante la comparticion de objetos.

Motivacion:

```
Los caracteres de un procesador de palabras podrian ser objetos.
La cantidad de caracteres en un documento puede ser muy grande.
Cada caracter es compartido por los objetos que lo contienen.
```

Ventajas: Reduce en gran cantidad el peso de los datos en un servidor

Desventajas: Consume un poco más de tiempo para realizar las búsquedas

**Pasos para aplicar el patrón**
1. Asegúrese que el rendimiento en los objetos es un tema primordial, y si el cliente está dispuesto a asumir el reajuste
2. Divida el objetivo principal en estados: Estado Intrínseco (elementos que se puedan compartir o son comunes) y Estado Extrínseco (elementos particulares a cada tipo)
3. Retire los elementos con estado extrínseco de los atributos de la clase, y añádale más bien una llamada a métodos
4. Crear una fábrica que pueda almacenar y reutilizar las instancias existentes de clases
5. El cliente debe usar la fábrica en vez de utilizar el operador new si requiere de creación de objetos
6. El cliente (o un tercero) debe revisar los estados extrínsecos, y reemplazar esos estados a métodos de la clase

**Comment by cristhiancr56** [comment]
![450px-flyweight_uml_class_diagram svg](https://cloud.githubusercontent.com/assets/16788720/17951517/8a909fcc-6a17-11e6-8bc6-e210ecb249ca.png)

**Comment by IoTeacher** [comment]
@cristhiancr56  liberado con 100.
