### ISSUE TITLE
Composite

### ISSUE THREAD

**Issue by damarcusfuentes** [tectijuana/pdd6a-archivado#29]
El patrón Composite nos permite construir objetos complejos partiendo de otros más sencillos utilizando una estrategia de composición recursiva. Podemos equiparar este patrón a un panel y sus celdas. Cada objeto simple (celda) puede relacionarse con otros formando una estructura más compleja (panel). Lo podemos ver también como un libro cada hoja (objeto sencillo) se puede relacionar con otras hojas y forman un libro (objeto compuesto).

Por otro lado, esta composición está encapsulada respecto a los clientes de los objetos que pueden interactuar sin tener que conocer la profundidad de la composición.

**Comment by damarcusfuentes** [comment]
![uml composite](https://cloud.githubusercontent.com/assets/21113395/17996335/f5fb94e6-6b1c-11e6-9062-8ab78aa4bdbf.jpg)

**Comment by damarcusfuentes** [comment]
![patron](https://cloud.githubusercontent.com/assets/21113395/18019685/06e97a1e-6b92-11e6-9d79-2766c0291caf.jpg)

Component: Declara la interfaz para los objetos de la composición, es la interfaz de acceso y manipulación de los componentes hijo e implementa algunos comportamientos por defecto.

Client: Manipula objetos atravez de la interfaz proporcionada por Component.

Composite: Define el comportamiento de los componentes compuestos, almacena a los hijos e implementa las operaciones de manejo de los componentes.

Leaf: Definen comportamientos para objetos primitivos del compuesto.

**Comment by damarcusfuentes** [comment]
![libro programa](https://cloud.githubusercontent.com/assets/21113395/18020237/4547f8c8-6b95-11e6-812b-a554b516cde7.jpg)

Ejemplo:
Problema: Actualmente a un escritor se le solicita escribir diferentes hojas, por cada hoja que escriba recibe un monto diferente y también se le solicita escribir un libro, pero se desconoce la cantidad de hojas que posee el libro, pero se requiere en algún momento solicitar el precio, ya sea de la hoja individual o del libro.

Solución:
Básicamente lo que necesitamos es que la hoja como el libro tenga  métodos común que sea obtener costo y agregar a la lista, el método obtener costos nos devuelve el costo ya sea por la hoja o por el libre, el libro debe poseer un lista de  AbstractCompositor a fin de agregar hoja por hoja.

using System;
using System.Collections.Generic;

namespace  Rextester;
{
    public class Program
    {
        static void Main(string[] args)
        {
            Compuesto raiz = new Compuesto("root");
            raiz.Agregar(new Hoja("hoja A"));
            raiz.Agregar(new Hoja("hoja B"));
            Compuesto comp = new Compuesto("compuesto X");
            comp.Agregar(new Hoja("hoja XA"));
            comp.Agregar(new Hoja("hoja XB"));
            raiz.Agregar(comp);
            raiz.Agregar(new Hoja("hoja C"));
            Hoja l = new Hoja("hoja D");
            raiz.Agregar(l);
            raiz.Eliminar(l);
            raiz.Mostrar(1);
            }
    }

```
public abstract class Componente
{
    protected string nombre;
    public Componente (string nombre)
    {
        this.nombre = nombre;
    }
    public abstract void Agregar(Componente componente);
    public abstract void Eliminar(Componente componente);
    public abstract void Mostrar(int profundidad);
}

public class Compuesto: Componente
{
    private List<Componente> hijo = new List<Componente>();
    public Compuesto (string nombre): base(nombre) { }
    public override void Agregar(Componente componente)
    {
        hijo.Add(componente);
    }
    public override void Eliminar(Componente componente)
    {
        hijo.Remove(componente);
    }
    public override void Mostrar(int profundidad)
    {
        Console.WriteLine(string.Format("{0} nivel: {1}", nombre, profundidad));
        for (int i = 0; i < hijo.Count; i++)
            hijo[i].Mostrar(profundidad + 1);
    }
}

public class Hoja: Componente
{
    public Hoja(string nombre): base(nombre) { }
    public override void Agregar(Componente componente)
    {
        Console.WriteLine("no se puede agregar la hoja");
    }
    public override void Eliminar(Componente componente)
    {
        Console.WriteLine("no se puede eliminar la hoja");
    }
    public override void Mostrar(int profundidad)
    {
        Console.WriteLine(string.Format("-{0}", nombre));
    }
}
```

}

**Comment by IoTeacher** [comment]
@damarcusfuentes Gracias creo que fue único?
