### ISSUE TITLE
Prototype.

### ISSUE THREAD

**Issue by tony528** [tectijuana/pdd6a-archivado#3]
:100: permite crear nuevos objetos por duplicacion de objetos existentes llamados prototipos que disponen de la capacidad de clonacion.
# Dominios de uso

El patrón Prototype se utiliza en los dominios siguientes
- un sistema de objetos debe crear instancias sin conocer la jerarquía de clases que las describe;
- un sistema de objetos debe crear instancias de clases dinámicamente;
- el sistema de objetos debe permanecer simple y no incluir una jerarquía paralela de clases de fabricación

**Comment by ghost** [comment]
![screenshot from 2016-08-24 16-30-11](https://cloud.githubusercontent.com/assets/15809538/17951587/22a5979a-6a18-11e6-85cb-49ad25a68cf1.png)

**Comment by tony528** [comment]
![uml](https://cloud.githubusercontent.com/assets/21091585/17875204/42ec6a2c-6885-11e6-941e-aa15de3e55a9.png)

**Comment by IoTeacher** [comment]
Gracias !!

**Comment by tony528** [comment]
saludos @IoTeacher

**Comment by tony528** [comment]
using System;

public abstract class Documento

{

protected string contenido = "";

public Documento duplica()

{

Documento resultado;

resultado = (Documento)this.MemberwiseClone();

return resultado;

}

public void rellena(string informacion)

{

contenido = informacion;

}

public abstract void imprime();

public abstract void visualiza();

}

using System;

public class OrdenDePedido : Documento

{

public override void visualiza()

{

Console.WriteLine("Muestra la orden de pedido: " +

contenido);

}

public override void imprime()

{

Console.WriteLine("Imprime la orden de pedido: " +

contenido);

}

}

using System;

public class SolicitudMatriculacion : Documento

{

public override void visualiza()

{

Console.WriteLine(

"Muestra la solicitud de matriculación: " + contenido);

}

public override void imprime()

{

Console.WriteLine(

"Imprime la solicitud de matriculación: " + contenido);

}

}

using System;

public class CertificadoCesion : Documento

{

public override void visualiza()

{

Console.WriteLine(

"Muestra el certificado de cesión: " + contenido);

}

public override void imprime()

{

Console.WriteLine(

"Imprime el certificado de cesión: " + contenido);

}

}

//El código fuente de la clase abstracta Documentacion es el siguiente:
using System.Collections.Generic;

public abstract class Documentacion

{

public IList documentos { get; protected set; }

}
using System.Collections.Generic;

public class DocumentacionEnBlanco : Documentacion

{

private static DocumentacionEnBlanco _instance = null;

private DocumentacionEnBlanco()

{

documentos = new List();

}

public static DocumentacionEnBlanco Instance()

{

if (_instance == null)

_instance = new DocumentacionEnBlanco();

return _instance;

}

public void incluye(Documento doc)

{

documentos.Add(doc);

}

public void excluye(Documento doc)

{

documentos.Remove(doc);

}

}

using System;

using System.Collections.Generic;

public class DocumentacionCliente : Documentacion

{

public DocumentacionCliente(string informacion)

{

documentos = new List();

DocumentacionEnBlanco documentacionEnBlanco = DocumentacionEnBlanco.Instance();

IList documentosEnBlanco =

documentacionEnBlanco.documentos;

foreach (Documento documento in documentosEnBlanco)

{

Documento copiaDocumento = documento.duplica();

copiaDocumento.rellena(informacion);

documentos.Add(copiaDocumento);

}

}

public void visualiza()

{

foreach (Documento documento in documentos)

documento.visualiza();

}

public void imprime()

{

foreach (Documento documento in documentos)

documento.imprime();

}

}

using System;

public class Usuario

{

static void Main(string[] args)

{

DocumentacionEnBlanco documentacionEnBlanco = DocumentacionEnBlanco.Instance();

documentacionEnBlanco.incluye(new OrdenDePedido());

documentacionEnBlanco.incluye(new CertificadoCesion());

documentacionEnBlanco.incluye(new SolicitudMatriculacion());

// creación de documentación nueva para dos clientes

DocumentacionCliente documentacionCliente1 = new DocumentacionCliente("Martín");

DocumentacionCliente documentacionCliente2 = new DocumentacionCliente("Simón");

documentacionCliente1.visualiza();

documentacionCliente2.visualiza();

}

}

**Comment by IoTeacher** [comment]
100 a @tony528 @Liryum

**Comment by ghost** [comment]
# CODIGO EN CSharp DEL PATRON PROTOTYPE

@IoTeacher  @tony528 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace Rextester
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("PATRON PROTOTYPE!!");
            DocumentacionEnBlanco documentacionEnBlanco = DocumentacionEnBlanco.Instance();
            documentacionEnBlanco.incluye(new OrdenDePedido());
            documentacionEnBlanco.incluye(new CertificadoCesion());
            documentacionEnBlanco.incluye(new SolicitudMatriculacion());
            // creación de documentación nueva para dos clientes
            DocumentacionCliente documentacionCliente1 = new DocumentacionCliente("Martín");
            DocumentacionCliente documentacionCliente2 = new DocumentacionCliente("Simón");
            documentacionCliente1.visualiza();
            documentacionCliente2.visualiza();
        }
    }  
    public abstract class Documento
    {
        protected string contenido = "";
        public Documento duplica()
        {
            Documento resultado;
            resultado = (Documento)this.MemberwiseClone();
            return resultado;
        }
    public void rellena(string informacion)
    {
        contenido = informacion;
    }
    public abstract void imprime();
    public abstract void visualiza();
    }  
    public class OrdenDePedido : Documento
    {
        public override void visualiza()
        {
            Console.WriteLine("Muestra la orden de pedido: " + contenido);
        }
        public override void imprime()
        {
            Console.WriteLine("Imprime la orden de pedido: " + contenido);
        }
    }  
    public class SolicitudMatriculacion : Documento
    {
        public override void visualiza()
        {
            Console.WriteLine("Muestra la solicitud de matriculación: " + contenido);
        }
        public override void imprime()
        {
            Console.WriteLine("Imprime la solicitud de matriculación: " + contenido);
        }
    }  
    public class CertificadoCesion : Documento
    {
        public override void visualiza()
        {
            Console.WriteLine("Muestra el certificado de cesión: " + contenido);
        }
        public override void imprime()
        {
            Console.WriteLine("Imprime el certificado de cesión: " + contenido);
        }
    }  
    public abstract class Documentacion
    {
        public IList<Documento> documentos { get; protected set; }
    }  
    public class DocumentacionEnBlanco : Documentacion
    {
        private static DocumentacionEnBlanco _instance = null;
        private DocumentacionEnBlanco()
        {
            documentos = new List<Documento>();
        }
        public static DocumentacionEnBlanco Instance()
        {
            if (_instance == null)
            _instance = new DocumentacionEnBlanco();
            return _instance;
        }
        public void incluye(Documento doc)
        {
            documentos.Add(doc);
        }
        public void excluye(Documento doc)
        {
            documentos.Remove(doc);
        }
    }
    public class DocumentacionCliente : Documentacion
    {
        public DocumentacionCliente(string informacion)
        {
            documentos = new List<Documento>();
            DocumentacionEnBlanco documentacionEnBlanco = DocumentacionEnBlanco.Instance();
            IList<Documento> documentosEnBlanco = documentacionEnBlanco.documentos;
            foreach (Documento documento in documentosEnBlanco)
            {
                Documento copiaDocumento = documento.duplica();
                copiaDocumento.rellena(informacion);
                documentos.Add(copiaDocumento);
            }
        }
        public void visualiza()
        {
            foreach (Documento documento in documentos)
            documento.visualiza();
        }
        public void imprime()
        {
            foreach (Documento documento in documentos)
            documento.imprime();
        }
    }  
}

**Comment by IoTeacher** [comment]
@tony528 y @Liryum  con 100 ya corrio el programa
