### ISSUE TITLE
Interpreter

### ISSUE THREAD

**Issue by alonsoitt** [tectijuana/pdd6a-archivado#30]
## **¿Que es?**

El patrón Interpreter proporciona un marco para representar mediante objetos la gramática de un lenguaje con el fin de evaluar, interpretándolas, expresiones escritas en este lenguaje.
## **Ejemplo**

Queremos crear un pequeño motor de búsqueda de vehículos con ayuda de expresiones booleanas según la gramática muy sencilla que se muestra a continuación:
expresión ::= término || palabra-clave || (expresión)
termino ::= factor ’o’ factor
factor ::= expresión ’y’ expresión
## **UML**

![capture](https://cloud.githubusercontent.com/assets/16808339/18059524/3099a698-6dce-11e6-8877-f0d913bd42a5.PNG)

@cesar4321

**Comment by cesar4321** [comment]
PARTICIPANTES:
Los participantes del patron son los siguientes:
- Expresión es una clase abstracta que representa cualquier tipo de expresión, es decir cualquier nodo
  del árbol sintáctico;
- OperadorAbstracto (OperadorBinario) es también una clase abstracta. Describe cualquier nodo de
  tipo operador, es decir que posea operandos que son subárboles del árbol sintáctico;
- OperadorConcreto1 y OperadorConcreto2 (OperadorY, OperadorO) son implementaciones del
- OperadorAbstracto que describen completamente la semántica del operador y por tanto son capaces
  de evaluarlo;
- ElementoTerminal es una clase abstracta que describe cualquier nodo correspondiente a un elemento
  terminal;
- ElementoTerminalConcreto1 y ElementoTerminalConcreto2 (PalabraClave) son clases concretas
  que corresponden con un elemento terminal, capaces de evaluar este elemento.

**Comment by cesar4321** [comment]
CODIGO

using System;
public abstract class Expresion
{
public abstract bool evalua(string descripcion);
// parte análisis sintáctico
protected static string fuente;
protected static int indice;
protected static string pieza;
protected static void siguientePieza()
{
while ((indice < fuente.Length) && (fuente[indice] ==
’ ’))
indice++;
if (indice == fuente.Length)
pieza = null;
else if ((fuente[indice] == ’(’) || (fuente[indice] ==
’)’))
{
pieza = fuente.Substring(indice, 1);
indice++;
}
else
{
int inicio = indice;
while ((indice < fuente.Length) && (fuente[indice] !=
’ ’) && (fuente[indice] != ’)’))
indice++;
pieza = fuente.Substring(inicio, indice - inicio);
}
}
public static Expresion analiza(string fuente)
{
Expresion.fuente = fuente;
indice = 0;
siguientePieza();
return OperadorO.parsea();
}
public static Expresion parsea()
{
Expresion resultado;
if (pieza == "(")
{
siguientePieza();
resultado = OperadorO.parsea();
if (pieza == null)
throw new Exception("Error de sintaxis");
if (pieza != ")")
throw new Exception("Error de sintaxis");
siguientePieza();
}
else
resultado = PalabraClave.parsea();
return resultado;
}
}
public class PalabraClave : Expresion
{
protected string palabraClave;
public PalabraClave(string palabraClave)
{
this.palabraClave = palabraClave;
}
public override bool evalua(string descripcion)
{
return descripcion.IndexOf(palabraClave) != -1;
}
// parte análisis sintáctico
public static new Expresion parsea()
{
Expresion resultado;
resultado = new PalabraClave(pieza);
siguientePieza();
return resultado;
}
}
public abstract class OperadorBinario : Expresion
{
protected Expresion operandoIzquierdo, operandoDerecho;
public OperadorBinario(Expresion operandoIzquierdo,
Expresion operandoDerecho)
{
this.operandoIzquierdo = operandoIzquierdo;
this.operandoDerecho = operandoDerecho;
}
}

public class OperadorO : OperadorBinario
public OperadorO(Expresion operandoIzquierdo,
Expresion operandoDerecho)
: base(operandoIzquierdo,
operandoDerecho) { }
public override bool evalua(string descripcion)
{
return operandoIzquierdo.evalua(descripcion) ||
operandoDerecho.evalua(descripcion);
}
// parte análisis sintáctico
public static new Expresion parsea()
{
Expresion resultadoIzquierdo, resultadoDerecho;
resultadoIzquierdo = OperadorY.parsea();
while ((pieza != null) && (pieza == "o"))
{
siguientePieza();
resultadoDerecho = OperadorY.parsea();
resultadoIzquierdo = new OperadorO(resultadoIzquierdo,
resultadoDerecho);
}
return resultadoIzquierdo;
}
}
public class OperadorY : OperadorBinario
{
public OperadorY(Expresion operandoIzquierdo,
Expresion operandoDerecho) : base(operandoIzquierdo,
operandoDerecho) { }
public override bool evalua(string descripcion)
{
return operandoIzquierdo.evalua(descripcion) &&
operandoDerecho.evalua(descripcion);
}
// parte análisis sintáctico
public static new Expresion parsea()
{
Expresion resultadoIzquierdo, resultadoDerecho;
resultadoIzquierdo = Expresion.parsea();
while ((pieza != null) && (pieza == "y"))
{
siguientePieza();
resultadoDerecho = Expresion.parsea();
resultadoIzquierdo = new OperadorY(resultadoIzquierdo,
resultadoDerecho);
}
return resultadoIzquierdo;
}
}

public class Usuario
{
static void Main(string[] args)
{
Expresion expresionConsulta = null;
Console.Write("Introduzca su consulta: ");
string consulta = Console.ReadLine();
try
{
expresionConsulta = Expresion.analiza(consulta);
}
catch (Exception e)
{
Console.WriteLine(e.Message);
expresionConsulta = null;
}
if (expresionConsulta != null)
{
Console.WriteLine(
"Introduzca la descripción de un vehículo: ");
string descripcion = Console.ReadLine();
if (expresionConsulta.evalua(descripcion))
Console.WriteLine(
"La descripción responde a la consulta");
else
Console.WriteLine("La descripción no responde a la consulta");
}
}
}

**Comment by cesar4321** [comment]
**CODIGO**

using System;
public abstract class Expresion

// la parte relativa a la evaluacion se limita a la declaracion de la firma del metodo evalua//
{
    public abstract bool evalua(string descripcion);
    // parte análisis sintáctico
    protected static string fuente;
    protected static int indice;
    protected static string pieza;
    protected static void siguientePieza()
    {
        while ((indice < fuente.Length) && (fuente[indice] == ' '))
            indice++;
        if (indice == fuente.Length)
            pieza = null;
        else if ((fuente[indice] == '(') || (fuente[indice] == ')'))
        {
            pieza = fuente.Substring(indice, 1);
            indice++;
        }
        else
        {
            int inicio = indice;
            while ((indice < fuente.Length) && (fuente[indice] !=
            ' ') && (fuente[indice] != ')'))
                indice++;
            pieza = fuente.Substring(inicio, indice - inicio);
        }
    }
    public static Expresion analiza(string fuente)
    {
        Expresion.fuente = fuente;
        indice = 0;
        siguientePieza();
        return OperadorO.parsea();
    }
    public static Expresion parsea()
    {
        Expresion resultado;
        if (pieza == "(")
        {
            siguientePieza();
            resultado = OperadorO.parsea();
            if (pieza == null)
                throw new Exception("Error de sintaxis");
            if (pieza != ")")
                throw new Exception("Error de sintaxis");
            siguientePieza();
        }
        else
            resultado = PalabraClave.parsea();
        return resultado;
    }
}

 //la clase concreta PalabraClave cuyo metodo evalua busca la palabra-clave en la descripcion//
public class PalabraClave : Expresion
{
    protected string palabraClave;
    public PalabraClave(string palabraClave)
    {
        this.palabraClave = palabraClave;
    }
    public override bool evalua(string descripcion)
    {
        return descripcion.IndexOf(palabraClave) != -1;
    }
    // parte análisis sintáctico
    public static new Expresion parsea()
    {
        Expresion resultado;
        resultado = new PalabraClave(pieza);
        siguientePieza();
        return resultado;
    }
}
 //la clase abstracta OperadorBinario gestiona los enlaces hacia los dos operandos del operador//
public abstract class OperadorBinario : Expresion
{
    protected Expresion operandoIzquierdo, operandoDerecho;
    public OperadorBinario(Expresion operandoIzquierdo,
    Expresion operandoDerecho)
    {
        this.operandoIzquierdo = operandoIzquierdo;
        this.operandoDerecho = operandoDerecho;
    }
}

 // la clase concreta OperadorO implementa el metodo evalua y gestiona el analisis de un termino//
public class OperadorO : OperadorBinario
{
    public OperadorO(Expresion operandoIzquierdo,
    Expresion operandoDerecho)
        : base(operandoIzquierdo,
        operandoDerecho) { }
    public override bool evalua(string descripcion)
    {
        return operandoIzquierdo.evalua(descripcion) ||
        operandoDerecho.evalua(descripcion);
    }
    // parte análisis sintáctico
    public static new Expresion parsea()
    {
        Expresion resultadoIzquierdo, resultadoDerecho;
        resultadoIzquierdo = OperadorY.parsea();
        while ((pieza != null) && (pieza == "o"))
        {
            siguientePieza();
            resultadoDerecho = OperadorY.parsea();
            resultadoIzquierdo = new OperadorO(resultadoIzquierdo,
            resultadoDerecho);
        }
        return resultadoIzquierdo;
    }
}

 // la clase concreta OperadorY implementa el metodo evalua y gestiona el analisis sintactico de un factor//
public class OperadorY : OperadorBinario
{
    public OperadorY(Expresion operandoIzquierdo,
    Expresion operandoDerecho)
        : base(operandoIzquierdo,
            operandoDerecho) { }
    public override bool evalua(string descripcion)
    {
        return operandoIzquierdo.evalua(descripcion) &&
        operandoDerecho.evalua(descripcion);
    }
    // parte análisis sintáctico
    public static new Expresion parsea()
    {
        Expresion resultadoIzquierdo, resultadoDerecho;
        resultadoIzquierdo = Expresion.parsea();
        while ((pieza != null) && (pieza == "y"))
        {
            siguientePieza();
            resultadoDerecho = Expresion.parsea();
            resultadoIzquierdo = new OperadorY(resultadoIzquierdo,
            resultadoDerecho);
        }
        return resultadoIzquierdo;
    }
}

 // la clase usuario implementa el programa principal//
public class Usuario
{
    static void Main(string[] args)
    {
        Expresion expresionConsulta = null;
        Console.Write("Introduzca su consulta: ");
        string consulta = Console.ReadLine();
        try
        {
            expresionConsulta = Expresion.analiza(consulta);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
            expresionConsulta = null;
        }
        if (expresionConsulta != null)
        {
            Console.WriteLine(
            "Introduzca la descripción de un vehículo: ");
            string descripcion = Console.ReadLine();
            if (expresionConsulta.evalua(descripcion))
                Console.WriteLine(
                "La descripción responde a la consulta");
            else
                Console.WriteLine(
                "La descripción no responde a la consulta");
        }
        Console.ReadKey();
    }
}

![patron interpreter](https://cloud.githubusercontent.com/assets/16788869/18253661/6ca2c4f8-734b-11e6-988d-d81cb26092aa.PNG)

@cesar4321 , @alonsoitt

**Comment by IoTeacher** [comment]
Con 100 ambos
