### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by BeatrizMendoza** [tectijuana/pdd6a-archivado#5]
Ejemplo de patron bridge

**Comment by BeatrizMendoza** [comment]
@dianarobles92 
@cindylu199

**Comment by dianarobles92** [comment]
Según el libro de GoF este patrón de diseño permite desacoplar una abstracción de su implementación, de manera que ambas puedan variar de forma independiente.

Supongamos que tenemos una clase abstracta en la que se define un método que deberá implementar cada clase que herede de ella: ¿cómo haríamos si una clase hija necesitase implementarlo de forma que realizase acciones diferentes dependiendo de determinadas circunstancias?.

En dichos casos nos resultaría útil el patrón Bridge (puente) ya que 'desacopla una abstracción' (un método abstracto) al permitir indicar (durante la ejecución del programa) a una clase qué 'implementación' del mismo debe utilizar (qué acciones ha de realizar).

El diagrama UML de este patrón es el siguiente:

<IMG SRC="http://informaticapc.com/patrones-de-diseno/images/bridge.jpg">

**Aplicaciones**
Evitar un enlace permanente entre la abstracción y su implementación.Esto puede ser debido a que la implementación debe ser seleccionada o cambiada en tiempo de ejecución.
Hacer que tanto las abstracciones como sus implementaciones deben ser extensibles por medio de subclases. En este caso, el patrón Bridge permite combinar abstracciones e implementaciones diferentes y extenderlas independientemente.
Los cambios en la implementación de una abstracción no deben impactar en los clientes, es decir, su código no debe tener que ser recompilado.
(En C++) Esconder la implementación de una abstracción completamente a los clientes. En C++, la representación de una clase es visible en la interface de la clase.
Compartir una implementación entre múltiples objetos (quizá usando contadores), y este hecho debe ser escondido a los clientes.

**Participantes**
Abstraction: define a una interfaz. Mantiene una referencia a un objeto de tipo Implementor.
RefinedAbstraction: extiende la interfaz definida por Abstraction.
Implementor: define la interfaz para la implementación de clases. Esta interfaz no se tiene que corresponder exactamente con la interfaz de Abstraction; de hecho, las dos interfaces pueden ser muy diferentes. Típicamente la interfaz Implementor provee sólo operaciones primitivas, y Abstraction define operaciones de alto nivel basadas en estas primitivas.
ConcreteImplementor: implementa la interfaz de Implementor y define su implementación concreta.

**Colaboraciones**
Abstraction emite los pedidos de los clientes a su objeto Implementor.

**Consecuencias**
1.Desacopla interface e implementación: una implementación no es limitada permanentemente a una interface. La implementación de una abstracción puede ser configurada en tiempo de ejecución. Además le es posible a un objeto cambiar su implementación en tiempo de ejecución. Desacoplando Abstraction e Implementor también elimina las dependencias sobre la implementación en tiempo de compilación. Cambiar una clase de implementación no require recompilar la clase Abstraction ni sus clientes. Esta propiedad es esencial cuando te debes asegurar la compatibilidad binaria entre diferentes versiones de una biblioteca de clases. Es más, este desacoplamiento fomenta las capas, que pueden conducir a un sistema mejor estructurado. La parte de alto nivel de un sistema sólo tiene que conocer Abstraction e Implementor.
2.Mejora la extensibilidad: se puede extender las jerarquías de Abstraction e Implementor independientemente.
3.Esconde los detalles de la implementación a los clientes.

**Comment by BeatrizMendoza** [comment]
Los patrones de diseño son el esqueleto de las soluciones a problemas comunes en el desarrollo de software. Brindan una solución ya probada y documentada a problemas de desarrollo de software que están sujetos a contextos similares. 
Dentro de los patrones estructurales se encuentra el bridge (puente) que Desacopla una abstracción de su implementación permitiendo modificarlas independientemente.
Bridge propone añadir un nuevo nivel de abstracción entre ambos elementos que permitan que puedan desarrollarse cada uno por su lado.

**Comment by BeatrizMendoza** [comment]
# Consecuencias

Las siguientes son consecuencias del uso del patrón Bridge: 
Desacopla la abstracción de su implementación. La abstracción no está permanentemente ligada a la implementación. La implementación puede ser configurada en tiempo de ejecución. Así mismo elimina dependencias en la compilación; es decir, cambios en una implementación, no requiere recompilación de la abstracción y su cliente.
Provee extensibilidad. La abstracción y la implementación pueden tener subclases independientemente.
Oculta detalles de implementación a los clientes.

# Implementación

Se deben considerar las siguientes situaciones cuando se aplica el patrón bridge: 

Solo un implementador. Cuando sólo hay una implementación, no es necesario crear una clase abstracta implementor. Sin embrago se puede hacer para mantener al cliente independiente de cambios en la implementación. 
Crear la implementación correcta. Si la abstracción conoce todas las implementaciones concretas, luego ésta puede instanciar una en su constructor, se decide entre las implementaciones, pasando un parámetro en el constructor. La forma en que se toma la decisión depende de las características de la implementación.

# Código ejemplo

El código ejemplo se basa en la abstracción de una operación sencilla, de dos números, las implementaciones son sumar, multiplicar y dividir.

//esta es la interfaz de la implementacion (implementor)
public interface Implementor {
public int operacion(int a, int b);
}
//esta es una implementación concreta (concretImplementor)
public class Sumar implements Implementor {
public int operacion(int a, int b) {
return a+b;
}
}
//esta es una implementación concreta (concretImplementor)
public class Multiplicar implements Implementor {
public int operacion(int a, int b) {
return a*b;
}
}
// esta es una implementación concreta (concretImplementor)
public class Dividir implements Implementor {
public int operacion(int a, int b) {
return a/b;
}
}
//esta es la interfaz de la abstraccion (abstraction)
public interface Abstraction {
public int operar(int num1, int num2);
}
//esta clase esxtiende la interfaz definida por abstraction (RedefinedAbstraction)
import operacion.Implementor;
public class RefinedAbstraction implements Abstraction {
Implementor implementacion=null;
public RefinedAbstraction(Implementor imp){
this.implementacion=imp;
}
public int operar(int num1, int num2) {
return implementacion.operacion(num1,num2);
}
}
//Es la clase cliente que utiliza la abstraccion (Client)
import operacion.Implementor;
import operacion.Abstraction;
public class Cliente {
public static void main(String[] args) {
int num1=4;
int num2=2;
Implementor [] imp= {new Sumar(),new Multiplicar(), new Dividir()};
Abstraction abst[] ={ new RefinedAbstraction(imp[0]), new RefinedAbstraction(imp[1]), new RefinedAbstraction(imp[2])};
for (int i=0; i<3;i++){
System.out.println(abst[i].operar(num1, num2));
}
}
}

# Usos conocidos

En ET++, se usa para la abstracción del tipo de ventana.
 Next’s AppKit usa el patrón en la implementación y representación de imágenes gráficas.

**Comment by dianarobles92** [comment]
## UML

<IMG SRC= "C:\Users\PC\Downloads\jpeg.jpg">

**Comment by dianarobles92** [comment]
<IMG SRC="http://www.dotnet-tricks.com/Content/images/designpatterns/bridge.png">

## 1. Abstraction
This is an abstract class and containing members that define an abstract business object and its functionality. It contains a reference to an object of type Bridge. It can also acts as the base class for other abstractions.
## 2. Redefined Abstraction
This is a class which inherits from the Abstraction class. It extends the interface defined by Abstraction class.
## 3. Bridge
This is an interface which acts as a bridge between the abstraction class and implementer classes and also makes the functionality of implementer class independent from the abstraction class.

## 4. ImplementationA & ImplementationB
These are classes which implement the Bridge interface and also provide the implementation details for the associated Abstraction class.

**Comment by BeatrizMendoza** [comment]
![myimage-alt-tag](https://danielggarcia.files.wordpress.com/2014/03/031614_2328_patronesest1.png?w=620)

**Comment by IoTeacher** [comment]
Recomiendo que inicie con nuestro eBook oficial ya despues puede moverse a otras referencias.

**Comment by cindylu199** [comment]
## informacion de bridge

**Comment by BeatrizMendoza** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication3
{
    public abstract class Message
    {
        public IMessageSender MessageSender { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public abstract void Send();
    }

```
/// <summary>
/// The 'RefinedAbstraction' class
/// </summary>
public class SystemMessage : Message
{
    public override void Send()
    {
        MessageSender.SendMessage(Subject, Body);
    }
}

/// <summary>
/// The 'RefinedAbstraction' class
/// </summary>
public class UserMessage : Message
{
    public string UserComments { get; set; }

    public override void Send()
    {
        string fullBody = string.Format("{0}\nUser Comments: {1}", Body, UserComments);
        MessageSender.SendMessage(Subject, fullBody);
    }
}

/// <summary>
/// The 'Bridge/Implementor' interface
/// </summary>
public interface IMessageSender
{
    void SendMessage(string subject, string body);
}

/// <summary>
/// The 'ConcreteImplementor' class
/// </summary>
public class EmailSender : IMessageSender
{
    public void SendMessage(string subject, string body)
    {
        Console.WriteLine("Email\n{0}\n{1}\n", subject, body);
    }
}

/// <summary>
/// The 'ConcreteImplementor' class
/// </summary>
public class MSMQSender : IMessageSender
{
    public void SendMessage(string subject, string body)
    {
        Console.WriteLine("MSMQ\n{0}\n{1}\n", subject, body);
    }
}

/// <summary>
/// The 'ConcreteImplementor' class
/// </summary>
public class WebServiceSender : IMessageSender
{
    public void SendMessage(string subject, string body)
    {
        Console.WriteLine("Web Service\n{0}\n{1}\n", subject, body);
    }
}
class Program
{
    static void Main(string[] args)
    {
        IMessageSender email = new EmailSender();
        IMessageSender queue = new MSMQSender();
        IMessageSender web = new WebServiceSender();

        Message message = new SystemMessage();
        message.Subject = "Test Message";
        message.Body = "Hi, This is a Test Message";

        message.MessageSender = email;
        message.Send();

        message.MessageSender = queue;
        message.Send();

        message.MessageSender = web;
        message.Send();

        UserMessage usermsg = new UserMessage();
        usermsg.Subject = "Test Message";
        usermsg.Body = "Hi, This is a Test Message";
        usermsg.UserComments = "I hope you are well";

        usermsg.MessageSender = email;
        usermsg.Send();

        Console.ReadKey();
    }

}
```

}`

**Comment by IoTeacher** [comment]
Gracias @BeatrizMendoza , @dianarobles92 y @cindylu199 con 100

**Comment by IoTeacher** [comment]
Hubo problemas con el codigo favor de acondicionarlo.
