### ISSUE TITLE
Adapter

### ISSUE THREAD

**Issue by HernandezJoseLuis** [tectijuana/pdd6a-archivado#8]
# Adapter
## Permite crear nuevos objetos por duplicación de objetos existentes llamados prototipos que  disponen de la capacidad de clonación.

@HernandezJoseLuis , @randomjuan 

![l php](https://cloud.githubusercontent.com/assets/21091587/17989016/b79504e4-6ad6-11e6-9234-39742cef97aa.png)

using System;

namespace DoFactory.GangOfFour.Adapter.Structural

{

  /// <summary>

  /// MainApp startup class for Structural

  /// Adapter Design Pattern.

  /// </summary>

  class MainApp

  {

```
/// <summary>

/// Entry point into console application.

/// </summary>

static void Main()

{

  // Create adapter and place a request

  Target target = new Adapter();

  target.Request();



  // Wait for user

  Console.ReadKey();

}
```

  }

  /// <summary>

  /// The 'Target' class

  /// </summary>

  class Target

  {

```
public virtual void Request()

{

  Console.WriteLine("Called Target Request()");

}
```

  }

  /// <summary>

  /// The 'Adapter' class

  /// </summary>

  class Adapter : Target

  {

```
private Adaptee _adaptee = new Adaptee();



public override void Request()

{

  // Possibly do some other work

  //  and then call SpecificRequest

  _adaptee.SpecificRequest();

}
```

  }

  /// <summary>

  /// The 'Adaptee' class

  /// </summary>

  class Adaptee

  {

```
public void SpecificRequest()

{

  Console.WriteLine("Called SpecificRequest()");

}
```

  }

}

**Comment by IoTeacher** [comment]
Debe de recortar para eso un buen editor es http://pixlr.com/editor y falta UML del eBOOK

**Comment by IoTeacher** [comment]
@HernandezJoseLuis falta acondicionar el PDD para la categoria. 
Checar los Milestones (Objetivos)

**Comment by HernandezJoseLuis** [comment]
No entiendo realmente que debo hacer profesor. No lo tengo claro

**Comment by IoTeacher** [comment]
Si claro joven Hdz. 

Bajar el libro oficial de la materia,
Leer capitulo 1
Leer su patron para este caso Adapter
Abrir el CASO (ya esta abierto, aqui estamos)
Leer y parafrasear ¿que es su patron? (Libro)
Drag & drop, el UML de su patron aqui a este Caso. 
Ejecutar su codigo fuente ejemplo c# (otras ocasiones serán otros lenguajes)
Si funciona, y comprueban la teoria y la ejecución, subir el codigo fuente al GIT creando su directorio adapter (cual sea el caso)
Redactar en este caso, sus conclusiones y claro investigando donde se podria utilizar su patrón.

**Comment by IoTeacher** [comment]
Que tal jovenes @HernandezJoseLuis , @randomjuan que nos platican del PDD ?

**Comment by IoTeacher** [comment]
Muchas gracias con 100
